version: "3.1"
services:
  postgres:
    image: mdillon/postgis:10-alpine
    ports:
    - 5433:5432
    volumes:
    - pgdata1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: change_me@!#2131
    networks:
    - local_net
  redis:
    image: redis:3-alpine
    ports:
      - 6378:6379
    networks:
      - local_net
  nginx:
    build:
      context: ./docker/nginx
    links:
    - php
    ports:
    - 8081:80
    networks:
    - local_net
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./:/var/www/html/
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - ./:/var/www/html/
    networks:
    - local_net
  php_worker:
    build:
      context: ./
      dockerfile: ./docker/supervisor/Dockerfile
    restart: always
    volumes:
      - ./docker/supervisor/queue.conf:/etc/supervisor/queue.conf
      - ./:/var/www/html/
    networks:
      - local_net
networks:
  local_net:
    driver: bridge
volumes:
  pgdata1:
    driver: local